#!/usr/bin/env python3
"""Create OpenClaw multi-agent task cards and ownership metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from datetime import datetime, timezone

DEFAULT_BLOCKED_PATHS = [
    ".env",
    ".env.*",
    ".npmrc",
    ".pypirc",
    ".netrc",
    "~/.ssh/**",
    "~/.codex/auth.json",
    "**/*.pem",
    "**/*.key",
]

DEFAULT_BLOCKED_COMMANDS = [
    "npm install",
    "pnpm install",
    "git push",
    "git reset --hard",
    "deploy",
    "publish",
]

MODULE_PATHS = {
    "backend": ["server/**", "backend/**", "api/**"],
    "frontend": ["client/**", "frontend/**", "web/**", "src/**"],
    "tests": ["tests/**", "test/**", "__tests__/**", "**/*.test.*", "**/*.spec.*"],
    "docs": ["docs/**", "README.md"],
}


def task_id(index: int) -> str:
    return f"T{index:03d}"


def write_card(path: Path, task: dict) -> None:
    lines = [
        f"task_id: {task['task_id']}",
        f"session_name: {task['session_name']}",
        f"runtime: {task['runtime']}",
        f"mode: {task['mode']}",
        f"role: {task['role']}",
        f"title: {task['title']}",
        f"objective: {task['objective']}",
        "context: Generated by create_task_cards.py",
        "dependencies: []",
        "allowed_paths:",
    ]
    lines.extend(f"  - {item}" for item in task["allowed_paths"])
    lines.append("blocked_paths:")
    lines.extend(f"  - {item}" for item in task["blocked_paths"])
    lines.append("allowed_commands:")
    lines.extend(f"  - {item}" for item in task["allowed_commands"])
    lines.append("blocked_commands:")
    lines.extend(f"  - {item}" for item in task["blocked_commands"])
    lines.append("may_use_skills:")
    if task["may_use_skills"]:
        lines.extend(f"  - {item}" for item in task["may_use_skills"])
    else:
        lines.append("  []")
    lines.extend(
        [
            "may_spawn_sessions: false",
            "validation_required:",
        ]
    )
    lines.extend(f"  - {item}" for item in task["validation_required"])
    lines.extend(
        [
            "stop_conditions:",
            "  - Need to edit outside allowed_paths",
            "  - Need secret or credential access",
            "  - Need dependency installation",
            "  - Need deployment or production mutation",
            "  - User changes may be overwritten",
            f"completion_signal: \"<task_complete task_id='{task['task_id']}' status='completed'>\"",
            "output_format: result-report.md",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task", required=True, help="High-level user task")
    parser.add_argument("--mode", default="implement", choices=["research", "implement", "fix", "review", "refactor"])
    parser.add_argument("--modules", nargs="+", default=["backend", "frontend", "tests"], help="Module names")
    parser.add_argument("--out", default=".codex-multi-agent/tasks", help="Task-card output directory")
    parser.add_argument("--runtime", default="acp", choices=["acp", "subagent", "native"])
    parser.add_argument("--reviewers", nargs="*", default=["correctness", "security"], help="Reviewer focus areas")
    parser.add_argument("--review-skill", default="ssrd", help="Review skill to authorize for reviewers")
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    state_dir = out_dir.parent
    results_dir = state_dir / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    tasks: list[dict] = []
    index = 1

    for module in args.modules:
        allowed_paths = MODULE_PATHS.get(module, [f"{module}/**"])
        explorer = {
            "task_id": task_id(index),
            "session_name": f"explorer-{module}",
            "runtime": args.runtime,
            "mode": "research" if args.mode != "review" else "review",
            "role": "Explorer",
            "title": f"Explore {module}",
            "objective": f"Research {module} for: {args.task}",
            "allowed_paths": allowed_paths,
            "blocked_paths": DEFAULT_BLOCKED_PATHS,
            "allowed_commands": ["rg", "find", "ls"],
            "blocked_commands": DEFAULT_BLOCKED_COMMANDS,
            "may_use_skills": [],
            "validation_required": ["Report findings with file evidence"],
            "status": "pending",
        }
        tasks.append(explorer)
        write_card(out_dir / f"{explorer['task_id']}-{explorer['session_name']}.md", explorer)
        index += 1

        if args.mode in {"implement", "refactor", "fix"}:
            worker = {
                "task_id": task_id(index),
                "session_name": f"worker-{module}",
                "runtime": args.runtime,
                "mode": args.mode,
                "role": "Worker",
                "title": f"Implement {module}",
                "objective": f"Implement the {module} portion of: {args.task}",
                "allowed_paths": allowed_paths,
                "blocked_paths": DEFAULT_BLOCKED_PATHS,
                "allowed_commands": ["rg", "npm test", "pnpm test", "pytest"],
                "blocked_commands": DEFAULT_BLOCKED_COMMANDS,
                "may_use_skills": [],
                "validation_required": ["Run targeted validation when available"],
                "status": "pending",
            }
            tasks.append(worker)
            write_card(out_dir / f"{worker['task_id']}-{worker['session_name']}.md", worker)
            index += 1

    for focus in args.reviewers:
        reviewer = {
            "task_id": task_id(index),
            "session_name": f"reviewer-{focus}",
            "runtime": args.runtime,
            "mode": "review",
            "role": "Reviewer",
            "title": f"Review {focus}",
            "objective": f"Review {args.task} with focus on {focus}",
            "allowed_paths": ["**/*"],
            "blocked_paths": DEFAULT_BLOCKED_PATHS,
            "allowed_commands": ["rg", "git diff", "git status"],
            "blocked_commands": DEFAULT_BLOCKED_COMMANDS,
            "may_use_skills": [args.review_skill] if args.review_skill else [],
            "validation_required": ["Return findings by severity"],
            "status": "pending",
        }
        tasks.append(reviewer)
        write_card(out_dir / f"{reviewer['task_id']}-{reviewer['session_name']}.md", reviewer)
        index += 1

    ownership = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "task": args.task,
        "tasks": [
            {
                "task_id": item["task_id"],
                "session_name": item["session_name"],
                "role": item["role"],
                "allowed_paths": item["allowed_paths"],
                "blocked_paths": item["blocked_paths"],
                "status": item["status"],
            }
            for item in tasks
        ],
    }
    (state_dir / "ownership.json").write_text(json.dumps(ownership, indent=2), encoding="utf-8")
    print(json.dumps({"ok": True, "tasks": len(tasks), "out": str(out_dir), "ownership": str(state_dir / "ownership.json")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
